CREATE TABLE `fichas` (
	`id` varchar(64) NOT NULL,
	`tipo` text,
	`keyword` text,
	`url` text NOT NULL,
	`titulo` text,
	`snippet` text,
	`dominio` text,
	`institucion` text,
	`email` text,
	`telefono` text,
	`tiene_formulario` text,
	`plataforma_social` text,
	`username` text,
	`subreddit` text,
	`grupo_facebook` text,
	`fecha_detectada` timestamp,
	`prioridad` text,
	`propuesta_comunicativa` text,
	`canal_recomendado` text,
	`estado` text DEFAULT ('pendiente'),
	`procesada` text DEFAULT ('NO'),
	`fecha_contacto` timestamp,
	`fecha_creacion` timestamp NOT NULL DEFAULT (now()),
	`ultima_actualizacion` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fichas_id` PRIMARY KEY(`id`)
);
